### ISSUE TITLE
Reason for new complete update of website

### ISSUE THREAD

**Issue by DsChauhan08** [flameshot-org/flameshot-org.github.io#109]
After trying to find bugs in the website code, my friend told me he is not able to download the application (he's a non-programmer guy). I've too found the cause for lesser downloads.

##The Reason
It is really hard for other non programmer people to download the application easily. We lead them to a GitHub post and asks them to find their best downloads.

## Am I correct?
I actually have no idea if it is important for open-source projects be like that ....

## Best Possible solutions from my side :
We can directly make a installer which installs the app and it starts running on device. For windows a application file for Mac and linux what ever it is....

## Who am I..
#107 I made a contribution here and I think i can contribute to this new method too

##Answer Me Other Contributor and Owner
@mmahmoudian 
@mmahmoudian

**Comment by mmahmoudian** [comment]
@DsChauhan08 
> We can directly make a installer which installs the app and it starts running on device. For windows a application file for Mac and linux what ever it is

Do you mean a standalone software to install another software? Would you please elaborate more

> he is not able to download the application (he's a non-programmer guy)

Not knowing the install format of the operating system is clearly a big shortfall of the user. Windows users since bigbang have been downloading `.exe` (and later `.msi`) files from internet to install software. OSX and macOS people have been downloading `.dmg` as far back as I can remember. If they don't even know that, how did they manage to install other software on their machine?

As for Linux users and more tech savvy mac users, terminal and software centers have been the primary way.

These days everyone can use a single command on their OS of choice to install software (windows: choco, Scoop, ... ; mac: brew, macport; Linux: the distro's package manager, flatpak, snap). 

We are definitely open to suggestions, but two very important notes:
1. Operating system is a tool, and like any other tool, it is responsibility of the user to know the elementary ways of operation (like you should grab the handle of hammer while using it)
2. It does not solve anything if we have to maintain yet another software, which user again should download its latest version and etc. It feels like classic example of recursion


Let's hear your idea in details and discuss it further.

**Comment by DsChauhan08** [comment]
I'm Mentioning that when a User clicks on download button it redirects them to Our GitHub page from where we can Install he Zip file and Run it on our device. 

My Plans are that: 
When a user hits the download button he .msi or .exe file starts downloading or on macOS the .dmg file starts downloading in the directory of The computer that can be run and install the application on the device

**Comment by mmahmoudian** [comment]
If you can pull it off in a dynamic way so that we don't have to update all the URLs with every release please go ahead and make a sketch or proof of concept.

**Comment by DsChauhan08** [comment]
To update the .exe file for your application on GitHub, you will need to follow these steps:

Make the necessary changes to your application's source code.

Build the updated version of your application using a C++ compiler. This will create a new .exe file.

Commit the changes to your version control repository. If you are using Git, you can do this by running the git commit command. Be sure to include a commit message that describes the changes that you have made.

Push the changes to your repository on GitHub. If you are using Git, you can do this by running the git push command.

Navigate to the releases page for your repository on GitHub.

Click the "Draft a new release" button.

Enter the version number or name for the release in the "Tag version" field.

Attach the updated .exe file to the release by clicking the "Add assets" button and selecting the .exe file.

Enter a title and description for the release, describing the changes that have been made.

Click the "Publish release" button to make the updated .exe file available for download.

Once you have published the release, users will be able to download the updated .exe file from the releases page on GitHub.


> I hope this helps

**Comment by mmahmoudian** [comment]
Thank you for the explanation. Perhaps you would like to have a look to our workflows and adjust your vision on how Flameshot project is working:

https://github.com/flameshot-org/flameshot/tree/master/.github/workflows

As far as I understand, what you are explaining is irrelevant to this repository which is the website repo. This last comment of your also is irrelevant to what you initially proposed.

If you have an idea to **automate download process for users who land on our website**, then I'm very interested to know what you have in mind.

You can also create a mock-up HTML+JS page if you think conveying your message is easier that way.

All suggestions are welcome, but they should fit into the scope of the Flameshot project.
