### ISSUE TITLE
Incorrect scaling when Ubuntu is scaled to 125%

### ISSUE THREAD

**Issue by nemanjam** [flameshot-org/flameshot-org.github.io#110]
In this case screen scaling increases and I can select only left upper portion of the screen. Resolution is blurry too. Scale Ubuntu 22.04 to 125% and try it yourself.

**Comment by mmahmoudian** [comment]
Thanks for the report, but:
1. For a useful bug report uou should provide complete information of your system and monitor setup so that we can try to reproduce it and then fix it
2. This repository is our **website repository**, what you are reporting is about our software and not our website
3. This is already reported : https://github.com/flameshot-org/flameshot/issues/564
