### ISSUE TITLE
Issue couldn't be stated in main repo... so here

### ISSUE THREAD

**Issue by DsChauhan08** [flameshot-org/flameshot-org.github.io#118]
Just saw a headstart for the application.

1. Let's take our app and put it online on some more bigger stores 
      Ex. Microsoft store, App store 
      ... no problem if you don't want to.....

2. Why not I (social media marketing agency) do the free marketing campaigns like free 
    videos and graphics on social media. Handle social media accounts for you.

This is Like donation to the Project so can I help?

And other ideas will be coming soon.....

**Comment by DsChauhan08** [comment]
@mmahmoudian @Breakthrough @leereilly @luzfcb 
What do you all say?

**Comment by mmahmoudian** [comment]
@DsChauhan08 please either clarify this issue or I have to mark it as Spam.

**Comment by mmahmoudian** [comment]
> Let's take our app and put it online on some more bigger stores. Ex. Microsoft store, App store

1. I don't give the slightest c...p about microsoft and would rather stay as far as possible from it. Other devs have also been sharing the same view.

2. We have collectively decided not to pay Apple tax, so that is clearly out of the picture

> Why not I (social media marketing agency) do the free marketing campaigns like free
videos and graphics on social media. Handle social media accounts for you.

You of course can. We have our Mastodon account and it is pretty active, and we have our peertube channel which is not active yet. If you want to create content and contribute, you are more than welcome.

> This is Like donation to the Project so can I help?

As have been mentioned many times, any contribution is welcome. So feel free to discuss and then implement/perform.

**Comment by DsChauhan08** [comment]
sure! was trying to find a faster way for a reply. See i got you there you replied pretty fast though.

I believe that flameshot is another level application and i use it (as a developer).
Tagging all these interesting people to make them react to it faster 
btw... 
sorry

**Comment by mmahmoudian** [comment]
Now I'm puzzled now. Why did you close this, and what happened to the rest of your idea?!

**Comment by DsChauhan08** [comment]
oh i am thinking and when new ideas will come i'll contact you
