### ISSUE TITLE
problem with share this screenshot with the requesting application ubuntu 22.04

### ISSUE THREAD

**Issue by StarScream902** [flameshot-org/flameshot-org.github.io#124]
I had Ubuntu 20.04 and after upgrade to 22.04 I encountered with this problem...
And solution by link below helped me
https://github.com/flameshot-org/flameshot/issues/2560#issuecomment-1223943716
in file `/etc/gdm3/custom.conf` I just uncommented the line `WaylandEnable=false` in section `[daemon]`
restart and vuala

**Comment by mmahmoudian** [comment]
Thanks for the post but:
1. Ubuntu and Gnome are two different things. Your issue is with Gnome and not Ubuntu. any other more sensible flavors of Ubuntu do not have this behavior
2. have you read our documentation? https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
3. switching to x11 is not a solution, it is just a by-pass. Our Wayland support is not ideal, but I hope you understand the changes you made and it's implications
4. in the *new* Gnome Wayland now you tell Gnome to remember your decision, so you need to just put a checkmark in the correct box to tell Gnome to remember sharing so it does not bother you again (like what we have had for about a decade in any of iPhone, Android, macOS, ...) .


Unfortunately Gnome during the past few years has made lots of weird decisions that have put users into issues. Unfortunately some popular Linux distros default to Gnome which is a shame because they are putting new Linux users into the misery of facing and solving these issues.
